'''
Codifies the court and tribunal abbreviations used in the McGill 9th edition as
dictionaries and numpy arrays.
'''

import numpy as np

b2_1_frequent_court_abbreviations = {
    "Cour d'appel": "CA",
    "Cour provinciale": "CP",
    "Cour supérieure": "CS",
    "Cour suprême du Canada": "CSC",
    "Court of Appeal": "CA",
    "Court of Justice": "CJ",
    "Federal Court of Appeal": "FCA",
    "High Court": "HC",
    "Provincial Court": "Prov Ct",
    "Superior Court": "Sup Ct",
    "Traffic Court": "Traffic Ct",
    "Youth Court": "Youth Ct"
}

b2_2_canadian_court_abbreviations = {
    "Coroners Court": "Cor Ct",
    "Cour canadienne de l'impôt": "CCI",
    "Cour d'appel": "CA",
    "Cour d'appel de la cour maritale": "CACM",
    "Cour d'appel fédérale": "CAF",
    "Cour de comité": "Cc",
    "Cour de l'Ontario, division générale": "Div gén Ont",
    "Cour des divorces et des causes matrimoniales": "C div & causes mat",
    "Cours des juges de la Cour de comté siégeant au criminel": "C j Cc crim",
    "Cours des petites créances": "C pet cré",
    "Cours des successions": "C succ",
    "Cour divisionnaire": "C div",
    "Cour du Banc de la Reine": "BR",
    "Cour du Banc de la Reine (Division de la famille)": "BR (div fam)",
    "Cour du Banc de la Reine (Division de première instance)":
        "BR (1re inst)",
    "Cour du Québec": "CQ",
    "Cour du Québec, Chambre civile": "CQ civ",
    "Cour du Québec, Chambre civile (Divisilon des petites créances)":
        "CQ civ (div pet cré)",
    "Cour du Québec, Chambre criminelle et pénale": "CQ crim & pén",
    "Cour du Québec, Chambre des jeunes": "CQ jeun",
    "Cour fédérale, première instance": "CF (1re inst)",
    "Cour municipale": "CM",
    "Cour provincial": "CP",
    "Cour provinciale (Division civile)": "CP Div civ",
    "Cour provinciale (Division criminelle)": "CP Div crim",
    "Cour provinciale (Division de la famille)": "CP Div fam",
    "Cour supérieure": "CS",
    "Cour supérieure (Chambre administrative)": "CS adm",
    "Cour supérieure (Chambre civile)": "CS civ",
    "Cour supérieure (Chambre criminel et pénale)": "CS crim & pén",
    "Cour supérieure (Chambre de la faillite et de l'insolvabilité)":
        "CS fail & ins",
    "Cour supérieure (Chambre de la famille)": "CS fam",
    "Cour supérieure (Division des petites créances)": "CS pet cré",
    "Cour suprême (Division d'appel)": "C supr A",
    "Cour suprême (Division de la famille)": "C supr fam",
    "Cour suprême (Division du Banc de la Reine)": "C supr BR",
    "Cour suprême du Canada": "CSC",
    "Court Martial Appeal Court": "Ct Martial App Ct",
    "Court of Appeal": "CA",
    "Court of Appeal in Equity": "CA Eq",
    "Court of Justice (General Division)": "Ct J (Gen Div)",
    "Court of Justice (General Division, Family Court)":
        "Ct J (Gen Di Fam Ct)",
    "Court of Justice (General Division, Small Claims Court)":
        "Ct J (Gen Div, Sm Cl Ct)",
    "Court of Justice (Provincial Division)": "Ct J (Prov Div)",
    "Court of Justice (Provincial Division, Youth Court)":
        "Ct J (Prov Div, Youth Ct)",
    "Court of King's Bench": "KB",
    "Court of King's Bench (Family Division)": "KB (Fam Div)",
    "Court of King's Bench (Trial Division)": "KB (TD)",
    "Court of Quebec": "CQ",
    "Court of Quebec (Civil Division)": "CQ (Civ Div)",
    "Court of Quebec (Civil Division, Small Claims)": "CQ (Civ Div Sm Cl)",
    "Court of Quebec (Criminal & Penal Division)": "CQ (Crim & Pen Div)",
    "Court of Quebec (Youth Division)": "CQ (Youth Div)",
    "Court of Queen's Bench": "QB",
    "Court of Queen's Bench (Family Division)": "QB (Fam Div)",
    "Court of Queen's Bench (Trial Division)": "QB (TD)",
    "Divisional Court": "Div Ct",
    "Divorce and Matrimonial Causes Court": "Div & Mat Causes Ct",
    "Federal Court (Trial Division)": "FCTD",
    "Federal Court of Appeal": "FCA",
    "High Court of Justice": "H Ct J",
    "Municipal Court": "Mun Ct",
    "Probate Court": "Prob Ct",
    "Provincial Court (Civil Division)": "Prov Ct (Civ Div)",
    "Provincial Court (Civil Division, Small Claims Court)":
        "Prov Ct (Civ Div Sm Cl Ct)",
    "Provincial Court (Criminal Division)": "Prov Ct (Crim Div)",
    "Provincial Court (Family Court)": "Prov Ct (Fam Ct)",
    "Provincial Court (Family Division)": "Prov Ct (Fam Div)",
    "Provincial Court (Juvenile Division)": "Prov Ct (Juv Div)",
    "Provincial Court (Small Claims Division)": "Prov Ct (Sm Cl Div)",
    "Provincial Court (Youth Court)": "Prov Ct (Youth Ct)",
    "Provincial Court (Youth Division)": "Prov Ct (Youth Div)",
    "Provincial Offences Court": "Prov Off Ct",
    "Small Claims Court": "Sm Cl Ct",
    "Superior Court (Administrative Division)": "Sup Ct (Adm Div)",
    "Superior Court (Bankruptcy and Insolvency Division)":
        "Sup Ct (Bank & Ins Div)",
    "Superior Court (Canada)": "Sup Ct",
    "Superior Court (Civil Division)": "Sup Ct (Civ Div)",
    "Superior Court (Criminal and Penal Division)": "Sup Ct (Crim & Pen Div)",
    "Superior Court (Family Division)": "Sup Ct (Fam Div)",
    "Superior Court (Small Claims Division)": "Sup Ct (Sm Cl Div)",
    "Supreme Court (Appellate Division) (Can provincial/Can Provinciale)": 
        "SC (AD)",
    "Supreme Court (Family Division)": "SC (Fam Div)",
    "Supreme Court (Queen's Bench Division)": "SC (QB Div)",
    "Supreme Court (Trial Division)": "SC (TD)",
    "Supreme Court of Canada": "SCC",
    "Tax Court of Canada": "TCC",
    "Tax Review Board": "T Rev B",
    "Territorial Court": "Terr Ct",
    "Territorial Court (Youth Court)": "Terr Ct Youth Ct"
}

b2_3_uk_courts = {
    "Chancery Court": "Ch",
    "Court of Justice (Scotland/Écosse)": "Ct Just",
    "Court of Sessions (Scotland/Écosse)": "Ct Sess",
    "High Court: Chancery Division (UK/R-U)": "ChD",
    "High Court; Family Division (UK/R-U)": "FamD",
    "High Court: Queen's Bench Division (UK/R-U)": "QBD",
    "High Court of Admiralty": "HC Adm",
    "High Court of Justice": "HCJ",
    "House of Lords (England/Angleterre)": "HL (Eng)",
    "House of Lords (Scotland/Écosse)": "HL (Scot)",
    "Judicial Committee of the Privy Council": "PC",
    "Stipendary Magistrate's Court": "Stip Mag Ct"
}

b2_4_us_courts = {
    "Administrative Court": "Admin Ct",
    "Admirality [Court, Division]": "Adm",
    "Alderman's Court": "Alder Ct",
    "Appeals Court": "App Ct",
    "Appellate Court": "App Ct",
    "Appellate Division": "App Div",
    "Bankruptcy [Court, Judge]": "Bankr",
    "Bankruptcy Appellate Panel": "BAP",
    "Board of Tax Appeals (US/É-U)": "BTA",
    "Borough Court": "[name] Bor Ct",
    "Chancery [Court, Division]": "Ch",
    "Children's Court": "Child Ct",
    "Circuit Court": "Cir Ct",
    "Circuit Court and Family Court": "Cir Ct & Fam Ct",
    "Circuit Court of Appeals (federal US/fédéral, É-U)": "Cir",
    "Circuit Court of Appeals (state)": "Cir Ct App",
    "Citizenship Appeals Court (US/É-U)": "Cit AC",
    "City and Parish Courts": "City & Parish Ct",
    "City Court": "[name] City Ct",
    "Civil Appeals": "Civ App",
    "Civil Court": "Civ Ct",
    "Civil Court of Record": "Civ Ct Rec",
    "Claims Court": "Cl Ct",
    "Commerce Court": "Comm Ct",
    "Common Pleas": "CP",
    "Commonwealth Court": "Commw Ct",
    "Conciliation Court": "Concil Ct",
    "Constitutional County Court": "Const County Ct",
    "County Court": "Co Ct",
    "County Court at Law": "County Ct at Law",
    "County Court Judges' Criminal Court": "Co Ct J Crim Ct",
    "County Judge's Court": "County J Ct",
    "County Recorder's Court": "County Rec Ct",
    "Court of [General, Special] Sessions": "Ct [Gen, Spec] Sess",
    "Court of Appeal[s] (state)": "Ct App",
    "Court of Appeals (federal)": "Cir",
    "Court of Chancery": "Ct Ch",
    "Court of Civil Appeals": "Ct Civ App",
    "Court of Claims": "Ct Cl",
    "Court of Common Pleas": "Ct Com Pl",
    "Court of Criminal Appeals": "Ct Crim App",
    "Court of Customs and Patent Appeals": "CCPA",
    "Court of Customs Appeals": "Ct Cust App",
    "Court of Errors": "Ct Err",
    "Court of Errors and Appeals": "Ct Err & App",
    "Court of Federal Claims": "Ct Fed Cl",
    "Court of First Instance": "Ct First Inst",
    "Court of International Trade": "Ct Intl Trade",
    "Court of Review": "Ct Rev",
    "Court of Special Appeals": "Ct Spec App",
    "Court of Tax Review": "Ct T Rev",
    "Criminal appeals": "Crim App",
    "Criminal District Court": "Crim Dist Ct",
    "Customs Court": "Cust Ct",
    "District Court (US Federal/É-U fédéral)": "D",
    "District Court (US states/États des É-U)": "Dist Ct",
    "District Court of Appeal[s]": "Dist Ct App",
    "District Justice Court": "Dist Just Ct",
    "Domestic Relations Court": "Dom Rel Ct",
    "Emergency Court of Appeal[s]": "Emer Ct App",
    "Environmental Court": "Env Ct",
    "Equity [Court, Division]": "Eq",
    "Family Court": "Fam Ct",
    "General Sessions Court": "Gen Sess Ct",
    "High Court": "High Ct",
    "Housing Court": "Housing Ct",
    "Intermediate Court of Appeals": "Intermed Ct App",
    "Justice Court": "J Ct",
    "Justice of the Peace's Court": "JP Ct",
    "Juvenile and Family Court": "Juv & Fam Ct",
    "Juvenile Court": "Juv Ct",
    "Juvenile Delinquency Court": "Juv Del Ct",
    "Land Court": "Land Ct",
    "Law Court": "Law Ct",
    "Magistrate Court": "Magis Ct",
    "Magistrate Division": "Magis Div",
    "Mayor's Court": "Mayor's Ct",
    "Municipal Court": "[name] Mun Ct",
    "Municipal Court not of Record": "Mun Ct not Rec",
    "Municipal Criminal Court of Record": "Mun Crim Ct Rec",
    "Orphans' Court": "Orphans' Ct",
    "Parish Court": "[name] Parish Ct",
    "Police Justice Court": "Police J Ct",
    
}
