'''
Codifies the jurisdiction abbreviations used in the McGill 9th edition as a
numpy array.
'''

import numpy as np

a1_canada_abbreviations_en = np.array([
    ["Jurisdiction", "Statutes and Gazettes", "Regulations",
    "Courts and Journals", "Neutral Citation", "Law Reporters",
    "Postal Abbreviation"],
    ["Alberta", "A", "Alta", "Alta", "AB", "A or ALta", "AB"],
    ["British Columbia", "BC", "BC", "BC", "BC", "BC", "BC"],
    ["Canada", "C", "C", "C or Can", "Can", "Can","-"],
    ["Lower Canada", "LC", "LC", "LC", "-", "LC","-"],
    ["Manitoba", "M", "Man", "Man", "MB", "Man", "MB"],
    ["New Brunswick", "NB", "NB", "NB", "NB", "NB", "NB"],
    ["Newfoundland", "N", "Nfld", "Nfld", "NF", "Nfld", "NL"],
    ["Newfoundland & Labrador", "NL", "NL", "NL", "NL", "Nfld", "NL"],
    ["Nova Scotia", "NS", "NS", "NS", "NS", "NS", "NS"],
    ["Northwest Territories", "NWT", "NWT", "NWT", "NWT or NT", "NWT", "NT"],
    ["Nunavut", "Nu", "Nu", "Nu", "NU", "Nu", "NU"],
    ["Ontario", "O", "O or Ont", "Ont", "ON", "O", "ON"],
    ["Prince Edward Island", "PEI", "PEI", "PEI", "PE", "PEI", "PE"],
    ["Province of Canada", "Prov C", "Prov C", "Prov C", "-", "-", "-"],
    ["Quebec", "Q", "Q", "Q (Journals) or Qc (Courts)", "QC", "Q", "QC"],
    ["Saskatchewan", "S", "S or Sask", "Sask", "SK", "Sask", "SK"],
    ["Upper Canada", "UC", "UC", "UC", "-", "UC", "-"],
    ["Yukon", "Y", "Y", "Y", "YK", "Y", "YT"],
])

a1_canada_abbreviations_fr = np.array([
    ["Indication geographique", "Lois et gazettes", "Règlements",
    "Cours et revues", "Référence neutre", "Recueils de droit", 
    "Abréviation postale"],
    ["Alberta", "A", "Alta", "Alta", "AB", "A or ALta", "AB"],
    ["British Columbia", "BC", "BC", "BC", "BC", "BC", "BC"],
    ["Canada", "C", "C", "C or Can", "Can", "Can", "-"],
    ["Lower Canada", "B-C", "B-C", "B-C", "-", "B-C", "-"],
    ["Manitoba", "M", "Man", "Man", "MB", "Man", "MB"],
    ["New Brunswick", "N-B", "N-B", "N-B", "NB", "N-B", "NB"],
    ["Newfoundland", "N", "Nfld", "Nfld", "NF", "Nfld", "NL"],
    ["Newfoundland & Labrador", "NL", "NL", "NL", "NL", "Nfld", "NL"],
    ["Nova Scotia", "NS", "NS", "NS", "NS", "NS", "NS"],
    ["Northwest Territories", "TN-O", "TN-O", "TN-O", "NWT or NT", "TN-O", 
     "NT"],
    ["Nunavut", "Nu", "Nu", "Nu", "NU", "Nu", "NU"],
    ["Ontario", "O", "O or Ont", "Ont", "ON", "O", "ON"],
    ["Prince Edward Island", "PEI", "PEI", "PEI", "PE", "PEI", "PE"],
    ["Province of Canada", "Prov C", "Prov C", "Prov C", "-", "-", "-"],
    ["Quebec", "Q", "Q", "Q (Journals) or Qc (Courts)", "QC", "Q", "QC"],
    ["Saskatchewan", "S", "S or Sask", "Sask", "SK", "Sask", "SK"],
    ["Upper Canada", "UC", "UC", "UC", "-", "UC", "-"],
    ["Yukon", "Y", "Y", "Y", "YK", "Y", "YT"],
])

a2_us_abbreviations_en = {
    "Alabama": "Ala", "Alaska": "Alaska", "Arizona": "Ariz", "Arkansas": "Ark",
    "California": "Cal", "Colorado": "Colo", "Connecticut": "Conn",
    "Delaware": "Del", "District of Columbia": "DC", "Florida": "Fla",
    "Georgia": "Ga", "Hawaii": "Hawaii", "Idaho": "Idaho", "Illinois": "Ill",
    "Indiana": "Ind", "Iowa": "Iowa", "Kansas": "Kan", "Kentucky": "Ky",
    "Louisiana": "La", "Maine": "Me", "Maryland": "Md", "Massachusetts": "Mass",
    "Michigan": "Mich", "Minnesota": "Minn", "Mississippi": "Miss",
    "Missouri": "Mo", "Montana": "Mont", "Nebraska": "Neb", "Nevada": "Nev",
    "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "N Mex",
    "New York": "NY", "North Carolina": "NC", "North Dakota": "N Dak",
    "Ohio": "Ohio", "Oklahoma": "Okla", "Oregon": "Or", "Pennsylvania": "Pa",
    "Rhode Island": "RI", "South Carolina": "SC", "South Dakota": "S Dak",
    "Tennessee": "Tenn", "Texas": "Tex", "United States": "US", "Utah": "Utah",
    "Vermont": "Vt", "Virginia": "Va", "Washington": "Wash", 
    "West Virginia": "W Va", "Wisconsin": "Wis", "Wyoming": "Wyo"
}

a2_us_abbreviations_fr = {"Alabama": "Ala", "Alaska": "Alaska", "Arizona": "Ariz",
    "Arkansas": "Ark", "California": "Cal", "Caroline du Nord": "NC",
    "Caroline du Sud": "SC", "Colorado": "Colo", "Connecticut": "Conn",
    "Dakota du Nord": "N Dak", "Dakota du Sud": "S Dak", "Delaware": "Del", 
    "District de Columbia": "DC", "Étas-Unis": "US", "Floride": "Fla",
    "Géorgie": "Ga", "Hawaï": "Hawaii", "Idaho": "Idaho", "Illinois": "Ill", 
    "Indiana": "Ind", "Iowa": "Iowa", "Kansas": "Kan", "Kentucky": "Ky",
    "Louisiane": "La", "Maine": "Me", "Maryland": "Md",
    "Massachusetts": "Mass", "Michigan": "Mich", "Minnesota": "Minn", 
    "Mississippi": "Miss", "Missouri": "Mo", "Montana": "Mont", 
    "Nebraska": "Neb", "Nevada": "Nev", "New Hampshire": "NH", 
    "New Jersey": "NJ", "New York": "NY", "Nouveau-Mexique": "N Mex",
    "Ohio": "Ohio", "Oklahoma": "Okla", "Oregon": "Or", "Pennsylvanie": "Pa",
    "Rhode Island": "RI", "Tennessee": "Tenn", "Texas": "Tex",
    "Utah": "Utah", "Vermont": "Vt", "Virginie": "Va", "Washington": "Wash",
    "Virginie occidentale": "W Va", "Wisconsin": "Wis", "Wyoming": "Wyo"
}

a3_australia_abbreviations_en = np.array([
    ["Jurisdiction", "Legislation and Courts", "Neutral citation"],
    ["Australia", "Austl", "-"],
    ["Commonwealth", "Cth", "-"],
    ["Australian Capital Territory", "ACT", "-"],
    ["New South Wales", "NSW", "NSW"],
    ["Northern Territory", "NT", "NT"],
    ["Queensland", "Qld", "Q"],
    ["South Australia", "SA", "SA"],
    ["Tasmania", "Tas", "TAS"],
    ["Victoria", "Vic", "V"],
    ["Western Australia", "WA", "WA"]
])

a3_australia_abbreviations_fr = np.array([
    ["Indication géographique", "Législation et cours", "Référence neutre"],
    ["Australie", "Austl", "-"],
    ["Commonwealth", "Cth", "-"],
    ["Territoire de la capitale australienne", "ACT", "-"],
    ["Nouvelle-Galles du Sud", "NSW", "NSW"],
    ["Territoire du Nord", "NT", "NT"],
    ["Queensland", "Qld", "Q"],
    ["Australie-Méridionale", "SA", "SA"],
    ["Tasmanie", "Tas", "TAS"],
    ["Victoria", "Vic", "V"],
    ["Australie-Occidentale", "WA", "WA"]
])

a4_other_abbreviations_en = {
    "European Union": "EU", "Hong Kong": "HK", "Ireland": "Irl",
    "New Zealand": "NZ", "Northern Ireland": "NI", "Scotland": "Scot", 
    "Singapore": "Sing", "South Africa": "S Afr", "United Kingdom": "UK",
    "United States": "US"
}

a4_other_abbreviations_fr = {
    "Afrique du Sud": "S Afr", "Écosse": "Scot", "États-Unis": "US",
    "Hong Kong": "HK", "Irlande": "Irl", "Irlande du nord": "IN",
    "Nouvelle-Zélande": "N-Z", "Royaume-Uni": "UK", "Singapour": "Sing",
    "Union européenne": "UE"
}

a5_international_material_abbreviations = {
    "Assemblée consultative (Conseil de l'Europe)": "AC",
    "Assemblée générale (NU)": "AG",
    "Agence internationale de l'énergie atomique (NU)": "AIEA",
    "Assemblée parlementaire (Conseil de l'Europe)": "AP",
    "Asia Pacific Economic Cooperation": "APEC",
    "Australia Treaty National INterest Analysis": "ATNIA",
    "Australian Treaty not yet in force": "ATNIF",
    "Australian Treaty Series": "ATS",
    "African Union": "AU",
    "Bureau (NU)": "Bur",
    "First Committee (UN) / Première Commission (NU)": "C1",
    "Second Committee (UN) / Deuxième Commission (NU)": "C2",
    "Third Committee (UN) / Troisième Commission (NU)": "C3",
    "Consultative Assembly (Council of Europe)": "CA",
    "Canada Treaty Series": "Can TS",
    "Conseil du commerce et du développement (NU)": "CCED",
    "Commission des droits de l'homme (NU)": "CDH",
    "Communautés européennes": "CE",
    "Conseil économique et social (NU)": "CES",
    "Cour internationale de justice": "CIJ",
    "Tribunal de première instance (CE)": "CJ (1re inst)",
    "Cour de justice des Communautés européennes": "CJE",
    "Conférence des Nations Unies sur le commerce et le développement": 
        "CNUCED",
    "Commission des Nations Unies pour le droit commercial international":
        "CNUDCI",
    "Commission européenne des DroiTs de l'Homme": "Comm Eur DH",
    "Commission interaméricaine des Droits de l'Homme": "Comm Interam DH",
    "Conseil de L'Europe": "Conseil de l'Europe",
    "Counsel of Europe": "Counsel of Europe",
    "Cour européenne des Droits de l'Homme": "Cour Eur DH",
    "Cour interamericaine des Droits de l'Homme": "Cour Interam DH",
    "Cour permanente de justice internationale": "CPJI",
    "Conseil de sécurité (NU)": "CS",
    "Conseil de tutele (NU)": "CT",
    "Consolidated Treaty Series": "CTS",
    "Decision": "Dec",
    "Décision": "Déc",
    "Document": "Doc",
    "Document officiel": "Doc off",
    "European Communities": "EC",
    "European Court of First Instance": "ECFI",
    "Court of Justice of the European Communities": "ECJ",
    "Emergency": "Emer",
    "Economic and Social Council (UN)": "ESC",
    "European Treaty Series": "ETS",
    "European Union": "EU",
    "European Commission of Human Rights": "Eur Comm HR",
    "European Court of Human Rights": "Eur Ct HR",
    "Extraordinaires": "Extra",
    "Fonds monétaire international (NU)": "FMI",
    "General Assembly (GA)": "GA",
    "Accord général sur les tarifs douaniers et le commerce": "GATT",
    "General Committee (UN)": "GC",
    "Haut-Commissariat aux droits de l'homme (NU)": "HCDH",
    "Haut-Commissariat des Nations Unies pour les réfugiés": "HCR",
    "Human Rights Committee (UN)": "HRC",
    "International Atomic Energy Agency (UN)": "IAEA",
    "International Civil Aviation Organization (NU)": "ICAO",
    "International Court of Justice": "ICJ",
    "International Criminal Tribunal for Rwanda": "ICTR",
    "International Criminal Tribunal for the former Yugoslavia (UN)": "ICTY",
    "International Legal Materials": "ILM",
    "International Labor Organization (UN)": "ILO",
    "International Monetary Fund (UN)": "IMF",
    "Inter-American Commission on Human Rights": "Inter-Am Comm HR",
    "Inter-American Court of Human Rights": "Inter-Am Ct HR",
    "League of Nations Treaty Series": "LNTS",
    "Mimeograph(ed)": "Mimeo",
    "Miméographié": "Miméo",
    "Meeting": "Mtg",
    "North Atlantic Treaty Organization": "NATO",
    "Nations Unies": "NU",
    "Conferérence des Nations Unies sur le commerce et le développement":
        "NUCED",
    "Organization de l'aviation civile internationale (NU)": "OACI",
    "Organization of American States": "OAS",
    "Organization of American States Treaty Series": "OASTS",
    "Organization des États américains": "OÉA",
    "United Nations High Commissioner for Human Rights, Office of the (UN)":
        "OHCHR",
    "Organisation international du travail (NU)": "OIT",
    "Organisation mondiale du commerce": "OMC",
    "Organisation mondiale de la propriété intellectuelle": "OMPI",
    "Official Records": "OR",
    "Organisation du Traité de l'Atlantique Nord": "OTAN",
    "Parliamentary Assembly (Council of Europe)": "PA",
    "Permanent Court of International Justice": "PCIJ",
    "Plenary": "Plen",
    "Plénière": "Plén",
    "Recommendation/Recomandation": "Rec",
    "Regulation": "Reg",
    "Resolution": "Res",
    "Résolution": "Rés",
    "Recueil des traités de la France": "RTF",
    "Recueil des traité des Nations Unies": "RTNU",
    "Recueil des traités du Canada": "RT Can",
    "Security Council": "SC",
    "Session": "Sess",
    "Special": "Spec",
    "Spécial": "Spéc",
    "Supplement": "Supp",
    "Série des traités européens": "STE",
    "Trusteeship Council": "TC",
    "Trade and Development Board (UN)": "TDB",
    "Treaties and other International Agreements of the United States of \
        America 1776-1949": "TI Agree",
    "United States Treaties and Other International Acts Series": "TIAS",
    "Tribunal pénal international pour le Rwanda": "TPR",
    "Tribunal pénal international pour l'ex-Yougoslavie": "TPIY",
    "Union africaine": "UA",
    "Union européenne": "UE",
    "British and Foreign State Papers": "UKFS",
    "United Kingdom Treaty Series": "UKTS",
    "United Nations": "UN",
    "United Nations Commission on International Trade Law": "UNCITRAL",
    "United Nations Conference on Trade and Development": "UNCTAD",
    "United Nations High Commissioner for Refugees": "UNHCR",
    "United Nations Treaty Series": "UNTS",
    "Urgence": "Urg",
    "United States Treaties and Other International Agreements": "USTA",
    "Banque mondiale/World Bank Organization": "WBO",
    "World Intellectual Property Organization": "WIPO",
    "World Trade Organization": "WTO"
}
